#ifndef METASHELLUIPLUGIN_GLOBAL_H
#define METASHELLUIPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(METASHELLUI_LIBRARY)
#  define METASHELLUIPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define METASHELLUIPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // METASHELLUIPLUGIN_GLOBAL_H
